apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJyZWdpc3RyeS5pbi5sdXhhaXIubHUiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImIzTmxibTkxWTJrNk1YQXdWakV4YVdJMSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJIdHRwSGVhZGVycyI6IHsKICAgICAgICAgICAgICAgICJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuNSAobGludXgpIgogICAgICAgIH0KfQ==
type: kubernetes.io/dockerconfigjson