apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: travel-ibe-api-replica
  labels:
    app: travel-ibe-api-replica
  #   tier: travel-ibe-api-replica
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: travel-ibe-api-replica
  template:
    metadata:
      labels:
        app: travel-ibe-api-replica
    spec:
      containers:
      - name: tavel-ibe-api
        image: luxairgroup.azurecr.io/scrum/travel-ibe:api4
        ports:
        - containerPort: 80